# Site settings
title: Random Notes
description: > # this means to ignore newlines until "baseurl:"
  "I'm a wanderer with an interest in programming, hardware, hacking,
  languages, food, coffee, science. This blog mostly serves as my private
  knowledgebase, but I figured it might be useful to others."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lunesu.com" # the base hostname & protocol for your site
twitter_username: LioLunesu
github_username:  lionello

# Build settings
markdown: kramdown
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
